apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loginapp
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: test-login-app
    repoURL: 'https://gitlab.com/grouptest6865038/manifest-repo.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
